source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'ILPDFKitTests' do
  inherit! :search_paths
  pod 'ILPDFKit', :path => '../'
  pod "Quick", "~> 0.10.0"
  pod "Nimble", "~> 5.1.0"
end
