
# Podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "13.0"
use_frameworks!


target "ILPDFKitExample" do
    pod "ILPDFKit", :path => '..'

    target "ILPDFKitUITests" do 
        inherit! :search_paths
    end
end

